DataDog\AuditBundle\Entity\Association:
  type: entity
  repositoryClass: DataDog\AuditBundle\Repository\AssociationRepository
  table: audit_associations
  id:
    id:
      type: bigint
      generator:
        strategy: IDENTITY

  fields:
    typ:
      length: 128
    tbl:
      length: 128
      nullable: true
    label:
      nullable: true
    fk:
      type: string
    class:
      type: string
    createdOn:
      type: datetime
