services:
  datadog.event_subscriber.audit:
    class: DataDog\AuditBundle\EventSubscriber\AuditSubscriber
    arguments: ["@security.token_storage"]
    tags:
      - { name: doctrine.event_subscriber, connection: default }

  datadog.event_listener.audit:
    class: DataDog\AuditBundle\EventListener\ControllerListener
    arguments: ['@service_container']
    tags:
      - { name: kernel.event_listener, event: kernel.controller }

