services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  DataDog\:
    resource: '../../../../../src/DataDog/*'
    # you can exclude directories or files
    # but if a service is unused, it's removed anyway
    exclude: '../../../../../src/DataDog/AuditBundle/{Entity,Repository,Service}'

  # actual services to be tagged as public
  DataDog\AuditBundle\Service\:
    resource: '../../../../../src/DataDog/AuditBundle/Service'
    public: true

  datadog.event_subscriber.audit:
    class: DataDog\AuditBundle\EventSubscriber\AuditSubscriber
    arguments: ["@security.token_storage"]
    tags:
      - { name: doctrine.event_subscriber, connection: default }

  datadog.event_listener.audit:
    class: DataDog\AuditBundle\EventListener\ControllerListener
    arguments: ['@service_container']
    tags:
      - { name: kernel.event_listener, event: kernel.controller }

